version: "3"
services:
  springboot-app3:
    container_name: c3
    image: player2
    restart: always
    build: .
    ports:
        - 8097:8096
    environment: 
      MYSQL_HOST: mysqldb6
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  c1:
    container_name: mysqldb6
    image: mysql
  
    ports:
       - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root   